spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AYBkGz+LUL/itkeDk6wHzYrFHvNnOUYcTLQZsw9A2FlLQkTGR1HgttxjDxDxJVJZQMvE1k3Dkt2J/X73HSmDWxzbchTiuSoyIMOvUnht0z8IYiOH7fy8ivCb/yofi5oN/3U2AEHSY4Dqd8h5xWtN4I2QFvImDMGg+8jipP0GHW7m90NPGGbLFpOh9qy6bZYDvs6CzSjQyp6C0f+76X8xNXlgQE1tkEeUIqyqMsOZEjR4YjEkIdnt7cQj5nkcxYmGvvqC5MXP6uzTw2mzB2TKydCvAE2GONkLhjK0xIorMascEeLp8oS8ohhpHNtAizRgn8sf4JsDo1fWPXHHYq2548DPvcCfaTmt4nbrekFZ01Su3DJFddQUB0z8q4th1cLQInE1JKrk0Zu1Esym3TPckUordSf+BAJRDJetAIvsljv3DHTgiVlbQZbcXRdQvTCJ1g4RXoNasw0bJfWCkiheTj9yjfiGdyZzYMIlo/ub1lDCJDV/83VNHN1cW+P6aUkEfQXRco1IBG3EwZUFA+bBzy1T33+2odHuB9LtLVIHTyfedw=='
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
